name: Auto deploy when push to main

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Deploy to remote
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ${{ secrets.DEPLOY_REMOTE_SERVER }}
          ftp-username: ${{ secrets.DEPLOY_REMOTE_USER }}
          ftp-password: ${{ secrets.DEPLOY_REMOTE_PASSWORD }}
          local-dir: dist
          git-ftp-args: --insecure